### ISSUE TITLE
Invalid React component state in Ticket.test.js

### ISSUE THREAD

**Issue by kevr** [kevr/breakscheduler#6]
```

> breakscheduler@0.1.0 test /home/kevr/dev/breakscheduler
> react-scripts test --env=jsdom-fourteen "Ticket.test.js"

  console.log src/components/ExtendedNavbar.js:7
    ExtendedNavbar Path: /help/support/ticket/1

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.warn node_modules/react-dom/cjs/react-dom.development.js:12357
    Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    
    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: SideEffect(NullComponent)

  console.log src/components/AuthenticationBarrier.js:9
    AuthenticationBarrier.componentDidMount

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/pages/help/support/AuthorizedRouter.js:9
    AuthorizedRouter.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/components/TicketBarrier.js:7
    TicketBarrier.componentDidMount

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Reply one","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"},{"id":2,"ticket_id":1,"body":"Reply two","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Reply one","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"},{"id":2,"ticket_id":1,"body":"Reply two","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/ExtendedNavbar.js:7
    ExtendedNavbar Path: /help/support/ticket/1

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/AuthenticationBarrier.js:9
    AuthenticationBarrier.componentDidMount

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/pages/help/support/AuthorizedRouter.js:9
    AuthorizedRouter.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/components/TicketBarrier.js:7
    TicketBarrier.componentDidMount

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/ReplyForm.js:40
    ReplyForm.handleSubmit

  console.log src/pages/help/support/Ticket.test.js:164
    preventDefault mock called

  console.error src/components/ReplyForm.js:97
    { Error: Request failed with status code 500
        at createErrorResponse (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:117:15)
        at Object.settle (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:97:16)
        at handleRequest (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/handle_request.js:42:13)
        at /home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:18:9
        at new Promise (<anonymous>)
        at MockAdapter.<anonymous> (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:17:14)
        at dispatchRequest (/home/kevr/dev/breakscheduler/node_modules/axios/lib/core/dispatchRequest.js:59:10)
      config:
       { url: 'http://localhost:5000/tickets/1/replies',
         method: 'post',
         data: '{"body":"Test reply","ticket_id":1}',
         headers:
          { Accept: 'application/json, text/plain, */*',
            'Content-Type': 'application/json;charset=utf-8' },
         transformRequest: [ [Function: transformRequest] ],
         transformResponse: [ [Function: transformResponse] ],
         timeout: 0,
         responseType: 'json',
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus] },
      response:
       { status: 500,
         data: undefined,
         headers: undefined,
         config:
          { url: 'http://localhost:5000/tickets/1/replies',
            method: 'post',
            data: '{"body":"Test reply","ticket_id":1}',
            headers: [Object],
            transformRequest: [Array],
            transformResponse: [Array],
            timeout: 0,
            responseType: 'json',
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus] } } }

  console.log src/components/ReplyForm.js:40
    ReplyForm.handleSubmit

  console.log src/pages/help/support/Ticket.test.js:181
    preventDefault mock called

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Test reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Test reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/Reply.js:34
    handleEdit called

  console.log src/components/Reply.js:36
    handleEdit end

  console.log src/components/Reply.js:34
    handleEdit called

  console.log src/components/Reply.js:36
    handleEdit end

  console.log src/components/Reply.js:27
    handleBodyChange called

  console.log src/components/Reply.js:29
    handleBodyChange end

  console.log src/components/Reply.js:72
    handleSave called

  console.log src/components/Reply.js:27
    handleBodyChange called

  console.log src/components/Reply.js:29
    handleBodyChange end

  console.log src/components/Reply.js:72
    handleSave called

  console.error src/components/Reply.js:102
    { Error: Request failed with status code 500
        at createErrorResponse (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:117:15)
        at Object.settle (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:97:16)
        at handleRequest (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/handle_request.js:42:13)
        at /home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:18:9
        at new Promise (<anonymous>)
        at MockAdapter.<anonymous> (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:17:14)
        at dispatchRequest (/home/kevr/dev/breakscheduler/node_modules/axios/lib/core/dispatchRequest.js:59:10)
      config:
       { url: 'http://localhost:5000/tickets/1/replies/1',
         method: 'patch',
         data:
          '{"id":1,"ticket_id":1,"body":"Test reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}',
         headers:
          { Accept: 'application/json, text/plain, */*',
            'Content-Type': 'application/json;charset=utf-8' },
         transformRequest: [ [Function: transformRequest] ],
         transformResponse: [ [Function: transformResponse] ],
         timeout: 0,
         responseType: 'json',
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus] },
      response:
       { status: 500,
         data: undefined,
         headers: undefined,
         config:
          { url: 'http://localhost:5000/tickets/1/replies/1',
            method: 'patch',
            data:
             '{"id":1,"ticket_id":1,"body":"Test reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}',
            headers: [Object],
            transformRequest: [Array],
            transformResponse: [Array],
            timeout: 0,
            responseType: 'json',
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus] } } }

  console.log src/components/Reply.js:72
    handleSave called

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Edited reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[{"id":1,"ticket_id":1,"body":"Edited reply","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/Reply.js:41
    handleDelete called

  console.log src/components/Reply.js:41
    handleDelete called

  console.error src/components/Reply.js:61
    { Error: Request failed with status code 500
        at createErrorResponse (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:117:15)
        at Object.settle (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:97:16)
        at handleRequest (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/handle_request.js:42:13)
        at /home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:18:9
        at new Promise (<anonymous>)
        at MockAdapter.<anonymous> (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:17:14)
        at dispatchRequest (/home/kevr/dev/breakscheduler/node_modules/axios/lib/core/dispatchRequest.js:59:10)
      config:
       { url: 'http://localhost:5000/tickets/1/replies/1',
         method: 'delete',
         data: null,
         headers: { Accept: 'application/json, text/plain, */*' },
         transformRequest: [ [Function: transformRequest] ],
         transformResponse: [ [Function: transformResponse] ],
         timeout: 0,
         responseType: 'json',
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus] },
      response:
       { status: 500,
         data: undefined,
         headers: undefined,
         config:
          { url: 'http://localhost:5000/tickets/1/replies/1',
            method: 'delete',
            data: null,
            headers: [Object],
            transformRequest: [Array],
            transformResponse: [Array],
            timeout: 0,
            responseType: 'json',
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus] } } }

  console.warn src/components/Reply.js:62
    Unable to delete Reply(1) in Ticket(1)
              with status code: undefined

  console.log src/components/Reply.js:41
    handleDelete called

  console.log src/components/Reply.js:56
    Deleted Reply(1) in Ticket(1)
              with status code: 200

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Ticket body","status":"open","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/ExtendedNavbar.js:7
    ExtendedNavbar Path: /help/support

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/pages/help/support/AuthorizedRouter.js:9
    AuthorizedRouter.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Dashboard.js:67
    searchTerms: 

  console.log src/components/Paginator.js:63
    
        Paginator.render
    
        page: 1
        dataSize: 1
        pageSize: 10
    
        pages: 1
        pageArray: 1
    
        

  console.log src/components/Paginator.js:63
    
        Paginator.render
    
        page: 1
        dataSize: 1
        pageSize: 10
    
        pages: 1
        pageArray: 1
    
        

  console.log src/pages/help/support/Dashboard.js:67
    searchTerms: 

  console.log src/components/Paginator.js:63
    
        Paginator.render
    
        page: 1
        dataSize: 1
        pageSize: 10
    
        pages: 1
        pageArray: 1
    
        

  console.log src/components/ExtendedNavbar.js:7
    ExtendedNavbar Path: /help/support/ticket/1

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/AuthenticationBarrier.js:9
    AuthenticationBarrier.componentDidMount

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/pages/help/support/AuthorizedRouter.js:9
    AuthorizedRouter.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/components/TicketBarrier.js:7
    TicketBarrier.componentDidMount

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.error src/components/TicketControl.js:65
    { Error: Request failed with status code 500
        at createErrorResponse (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:117:15)
        at Object.settle (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/utils.js:97:16)
        at handleRequest (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/handle_request.js:42:13)
        at /home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:18:9
        at new Promise (<anonymous>)
        at MockAdapter.<anonymous> (/home/kevr/dev/breakscheduler/node_modules/axios-mock-adapter/src/index.js:17:14)
        at dispatchRequest (/home/kevr/dev/breakscheduler/node_modules/axios/lib/core/dispatchRequest.js:59:10)
      config:
       { url: 'http://localhost:5000/tickets/1',
         method: 'patch',
         data: '{"id":1,"status":"closed"}',
         headers:
          { Accept: 'application/json, text/plain, */*',
            'Content-Type': 'application/json;charset=utf-8',
            Authorization: 'Token stubToken' },
         transformRequest: [ [Function: transformRequest] ],
         transformResponse: [ [Function: transformResponse] ],
         timeout: 0,
         responseType: 'json',
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus] },
      response:
       { status: 500,
         data: undefined,
         headers: undefined,
         config:
          { url: 'http://localhost:5000/tickets/1',
            method: 'patch',
            data: '{"id":1,"status":"closed"}',
            headers: [Object],
            transformRequest: [Array],
            transformResponse: [Array],
            timeout: 0,
            responseType: 'json',
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus] } } }

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"closed","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"closed","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"escalated","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"escalated","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}


  console.log src/components/ReplyForm.js:40
    ReplyForm.handleSubmit

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[{"id":10,"ticket_id":1,"body":"Blah","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"}}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"open","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[{"id":10,"ticket_id":1,"body":"Blah","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"}}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/components/ReplyForm.js:81
    { id: 1,
      subject: 'Test ticket',
      body: 'Test body',
      status: 'closed',
      user:
       { id: 2,
         name: 'Admin User',
         email: 'admin@example.com',
         type: 'admin' },
      replies: [ { id: 10, ticket_id: 1, body: 'Blah', user: [Object] } ],
      created_at: 'Thu, 12 Dec 2019 00:24:38 GMT',
      updated_at: 'Thu, 12 Dec 2019 00:24:38 GMT' }

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: [{"id":1,"subject":"Test ticket","body":"Test body","status":"closed","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[{"id":10,"ticket_id":1,"body":"Blah","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"}}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}]

  console.log src/pages/help/support/Ticket.js:59
    Rendering {"id":1,"subject":"Test ticket","body":"Test body","status":"closed","user":{"id":2,"name":"Admin User","email":"admin@example.com","type":"admin"},"replies":[{"id":10,"ticket_id":1,"body":"Blah","user":{"id":1,"name":"Test User","email":"test@example.com","type":"user"}}],"created_at":"Thu, 12 Dec 2019 00:24:38 GMT","updated_at":"Thu, 12 Dec 2019 00:24:38 GMT"}

  console.log src/pages/help/support/Ticket.js:20
    handleReply called resetState on TicketControl

  console.log src/components/ReplyForm.js:40
    ReplyForm.handleSubmit

  console.error node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
        in ReplyForm (created by ConnectFunction)
        in ConnectFunction (at ReplyCollapse.js:45)
        in div (at ReplyCollapse.js:44)
        in li (at ReplyCollapse.js:40)
        in ul (at ReplyCollapse.js:39)
        in ReplyCollapse (at Ticket.js:143)

  console.log src/components/ExtendedNavbar.js:7
    ExtendedNavbar Path: /help/support/ticket/666

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/AuthenticationBarrier.js:9
    AuthenticationBarrier.componentDidMount

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/pages/help/support/AuthorizedRouter.js:9
    AuthorizedRouter.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/components/TicketBarrier.js:7
    TicketBarrier.componentDidMount

  console.log src/actions/API.js:11
    Using token authorization: stubToken

  console.log src/components/AuthenticationBarrier.js:30
    AuthenticationBarrier.render

  console.log src/components/TicketBarrier.js:40
    TicketBarrier.render

  console.log src/pages/help/support/Ticket.js:26
    Ticket.render

  console.log src/pages/help/support/Ticket.js:31
    Tickets: []

  console.error src/pages/help/support/Ticket.js:38
    Rendering ticket page for ticket that does not exist

```

In the above test output from `npm test Ticket.test.js`, the following segment displays an error state component in our application, related to `ReplyForm`.

```

  console.error node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
        in ReplyForm (created by ConnectFunction)
        in ConnectFunction (at ReplyCollapse.js:45)
        in div (at ReplyCollapse.js:44)
        in li (at ReplyCollapse.js:40)
        in ul (at ReplyCollapse.js:39)
        in ReplyCollapse (at Ticket.js:143)
```

Before merging branches into `master`, we require all avoidable warnings to be silenced.

**Comment by kevr** [comment]
Fixed in https://github.com/kevr/breakscheduler/commit/9438da7e859f005a48b0b58262569a6c166e5b90
